import DeGiorgi.WeakFormulation.SmoothTests
import Mathlib.Analysis.InnerProductSpace.LaxMilgram

/-!
# Weak Formulation: Coefficient Operator

This module develops the `L²` coefficient action, the induced bilinear form on
closure of smooth gradient subspaces, and the bridge back to the Sobolev
bilinear form.
-/

noncomputable section

open MeasureTheory Filter
open scoped InnerProductSpace

namespace DeGiorgi

variable {d : ℕ} [NeZero d]

local notation "E" => AmbientSpace d

/-- The linear subspace of `L²(Ω; E)` generated by classical gradients of
smooth compactly supported test functions supported in `Ω`. -/
noncomputable def smoothGradSubmodule
    {Ω : Set E} (hΩ : IsOpen Ω) :
    Submodule ℝ (MeasureTheory.Lp E 2 (volume.restrict Ω)) where
  carrier := {G | ∃ u : E → ℝ, ∃ hu : IsSmoothTestOn Ω u, smoothGradToLp hΩ hu = G}
  zero_mem' := by
    exact ⟨fun _ : E => (0 : ℝ), IsSmoothTestOn.zero, smoothGradToLp_zero hΩ⟩
  add_mem' := by
    rintro G H ⟨u, hu, rfl⟩ ⟨v, hv, rfl⟩
    exact ⟨fun x => u x + v x, hu.add hv, smoothGradToLp_add hΩ hu hv⟩
  smul_mem' := by
    intro c G hG
    rcases hG with ⟨u, hu, rfl⟩
    exact ⟨fun x => c * u x, hu.smul c, smoothGradToLp_smul hΩ c hu⟩

private theorem matMulE_norm_le_of_mixed_bound
    {Ω : Set E} (A : EllipticCoeff d Ω) {x : E}
    (hx : ∀ ξ ζ : E, |⟪ζ, matMulE (A.a x) ξ⟫_ℝ| ≤ A.Λ * ‖ζ‖ * ‖ξ‖)
    (ξ : E) :
    ‖matMulE (A.a x) ξ‖ ≤ A.Λ * ‖ξ‖ := by
  let η : E := matMulE (A.a x) ξ
  by_cases hη : η = 0
  · simpa [η, hη] using mul_nonneg A.Λ_nonneg (norm_nonneg ξ)
  · have hη_pos : 0 < ‖η‖ := norm_pos_iff.mpr hη
    have hsq :
        ‖η‖ ^ (2 : ℕ) ≤ A.Λ * ‖η‖ * ‖ξ‖ := by
      simpa [η, real_inner_self_eq_norm_sq, abs_of_nonneg (sq_nonneg ‖η‖),
        pow_two, mul_assoc, mul_left_comm, mul_comm] using hx ξ η
    nlinarith [hsq, hη_pos, A.Λ_nonneg, norm_nonneg ξ]

private theorem ae_matMulE_norm_le
    {Ω : Set E} (A : EllipticCoeff d Ω) :
    ∀ᵐ x ∂(volume.restrict Ω), ∀ ξ : E,
      ‖matMulE (A.a x) ξ‖ ≤ A.Λ * ‖ξ‖ := by
  filter_upwards [A.mixed_bound] with x hx
  exact matMulE_norm_le_of_mixed_bound A hx

private theorem coeffAction_component_memLp
    {Ω : Set E} (A : EllipticCoeff d Ω)
    {g : E → E} (hg : MemLp g 2 (volume.restrict Ω)) (i : Fin d) :
    MemLp (fun x => matMulE (A.a x) (g x) i) 2 (volume.restrict Ω) := by
  refine MemLp.of_le_mul (g := fun x => ‖g x‖) (c := A.Λ) hg.norm ?_ ?_
  · have hmeas :
        AEMeasurable
          (fun x => ∑ j : Fin d, A.a x i j * (g x).ofLp j)
          (volume.restrict Ω) := by
      have hg_ofLp_cont : Continuous (fun y : E => (WithLp.ofLp y : Fin d → ℝ)) := by
        simpa using (PiLp.continuous_ofLp 2 (fun _ : Fin d => ℝ))
      have hg_ofLp :
          AEStronglyMeasurable (fun x => (WithLp.ofLp (g x) : Fin d → ℝ)) (volume.restrict Ω) :=
        hg_ofLp_cont.comp_aestronglyMeasurable hg.aestronglyMeasurable
      have hmeas_sum :
          AEMeasurable
            (∑ j : Fin d, fun x => A.a x i j * (g x).ofLp j)
            (volume.restrict Ω) := by
        refine Finset.aemeasurable_sum (s := (Finset.univ : Finset (Fin d)))
          (f := fun j x => A.a x i j * (g x).ofLp j) ?_
        intro j _
        have hgj : AEMeasurable (fun x => (g x).ofLp j) (volume.restrict Ω) := by
          simpa using
            (Continuous.comp_aestronglyMeasurable (continuous_apply j)
              hg_ofLp).aemeasurable
        exact (A.measurable_apply i j).aemeasurable.mul hgj
      convert hmeas_sum using 1
      ext x
      simp
    simpa [matMulE_apply, Matrix.mulVec] using hmeas.aestronglyMeasurable
  · filter_upwards [ae_matMulE_norm_le A] with x hx
    calc
      ‖matMulE (A.a x) (g x) i‖ ≤ ‖matMulE (A.a x) (g x)‖ := by
        simpa using (PiLp.norm_apply_le (matMulE (A.a x) (g x)) i)
      _ ≤ A.Λ * ‖‖g x‖‖ := by
            simpa using hx (g x)

private theorem coeffAction_memLp
    {Ω : Set E} (A : EllipticCoeff d Ω)
    {g : E → E} (hg : MemLp g 2 (volume.restrict Ω)) :
    MemLp (fun x => matMulE (A.a x) (g x)) 2 (volume.restrict Ω) := by
  refine MemLp.of_eval_piLp ?_
  intro i
  exact coeffAction_component_memLp A hg i

/-- The pointwise coefficient action viewed as an `L²` element. -/
private noncomputable def coeffApplyLp
    {Ω : Set E} (A : EllipticCoeff d Ω)
    (g : MeasureTheory.Lp E 2 (volume.restrict Ω)) :
    MeasureTheory.Lp E 2 (volume.restrict Ω) := by
  let hg : MemLp (fun x => g x) 2 (volume.restrict Ω) := Lp.memLp g
  let hAg : MemLp (fun x => matMulE (A.a x) (g x)) 2 (volume.restrict Ω) :=
    coeffAction_memLp A hg
  exact hAg.toLp (fun x => matMulE (A.a x) (g x))

private theorem coeffApplyLp_ae_eq
    {Ω : Set E} (A : EllipticCoeff d Ω)
    (g : MeasureTheory.Lp E 2 (volume.restrict Ω)) :
    coeffApplyLp A g =ᵐ[volume.restrict Ω] fun x => matMulE (A.a x) (g x) := by
  simpa [coeffApplyLp] using
    (MemLp.coeFn_toLp (coeffAction_memLp A (Lp.memLp g)))

/-- Pointwise coefficient action on `L²(Ω; E)`. -/
noncomputable def coeffMulLpL
    {Ω : Set E} (A : EllipticCoeff d Ω) :
    MeasureTheory.Lp E 2 (volume.restrict Ω) →L[ℝ]
      MeasureTheory.Lp E 2 (volume.restrict Ω) := by
  let f : MeasureTheory.Lp E 2 (volume.restrict Ω) →ₗ[ℝ]
      MeasureTheory.Lp E 2 (volume.restrict Ω) := {
    toFun := coeffApplyLp A
    map_add' := by
      intro g h
      apply Lp.ext
      let hAgh : MemLp (fun x => matMulE (A.a x) ((g + h) x)) 2 (volume.restrict Ω) :=
        coeffAction_memLp A (Lp.memLp (g + h))
      filter_upwards
        [MemLp.coeFn_toLp hAgh, coeffApplyLp_ae_eq A g, coeffApplyLp_ae_eq A h, Lp.coeFn_add g h,
          Lp.coeFn_add (coeffApplyLp A g) (coeffApplyLp A h)] with x hx_gh hx_g hx_h hx_add hx_sum
      have hpoint : matMulE (A.a x) ((g + h) x) = coeffApplyLp A g x + coeffApplyLp A h x := by
        rw [hx_add, hx_g, hx_h]
        ext i
        simp [matMulE_apply, Matrix.mulVec_add]
      exact hx_gh.trans (hpoint.trans hx_sum.symm)
    map_smul' := by
      intro c g
      apply Lp.ext
      filter_upwards
        [coeffApplyLp_ae_eq A (c • g), coeffApplyLp_ae_eq A g, Lp.coeFn_smul c g,
          Lp.coeFn_smul c (coeffApplyLp A g)] with x hx_cg hx_g hx_smul hx_out
      have hpoint : matMulE (A.a x) ((c • g) x) = c • coeffApplyLp A g x := by
        rw [hx_smul, hx_g]
        ext i
        simp [Pi.smul_apply, matMulE_apply, Matrix.mulVec_smul]
      exact hx_cg.trans (hpoint.trans hx_out.symm) }
  refine f.mkContinuous A.Λ ?_
  intro g
  apply Lp.norm_le_mul_norm_of_ae_le_mul
  filter_upwards [coeffApplyLp_ae_eq A g, ae_matMulE_norm_le A] with x hx_toLp hx_bound
  calc
    ‖coeffApplyLp A g x‖ = ‖matMulE (A.a x) (g x)‖ := by
      rw [hx_toLp]
    _ ≤ A.Λ * ‖g x‖ := hx_bound (g x)

theorem norm_coeffMulLpL_le
    {Ω : Set E} (A : EllipticCoeff d Ω)
    (g : MeasureTheory.Lp E 2 (volume.restrict Ω)) :
    ‖coeffMulLpL A g‖ ≤ A.Λ * ‖g‖ := by
  let hg : MemLp (fun x => g x) 2 (volume.restrict Ω) := Lp.memLp g
  let hAg : MemLp (fun x => matMulE (A.a x) (g x)) 2 (volume.restrict Ω) :=
    coeffAction_memLp A hg
  apply Lp.norm_le_mul_norm_of_ae_le_mul
  filter_upwards [MemLp.coeFn_toLp hAg, ae_matMulE_norm_le A] with x hx_toLp hx_bound
  calc
    ‖hAg.toLp (fun x => matMulE (A.a x) (g x)) x‖ = ‖matMulE (A.a x) (g x)‖ := by
      rw [hx_toLp]
    _ ≤ A.Λ * ‖g x‖ := hx_bound (g x)

/-- The coefficient bilinear form on a closed gradient subspace of
`L²(Ω; E)`. -/
noncomputable def coeffBilinSubmodule
    {Ω : Set E} (A : EllipticCoeff d Ω)
    (H : Submodule ℝ (MeasureTheory.Lp E 2 (volume.restrict Ω))) :
    H →L[ℝ] H →L[ℝ] ℝ := by
  refine LinearMap.mkContinuous₂
    (LinearMap.mk₂ ℝ
      (fun g h => ⟪coeffMulLpL A (H.subtypeL g), H.subtypeL h⟫_ℝ)
      (by intro g₁ g₂ h; simp [inner_add_left])
      (by intro c g h; simp [inner_smul_left])
      (by intro g h₁ h₂; simp [inner_add_right])
      (by intro c g h; simp [inner_smul_right]))
    A.Λ ?_
  intro g h
  calc
    ‖⟪coeffMulLpL A (H.subtypeL g), H.subtypeL h⟫_ℝ‖
        ≤ ‖coeffMulLpL A (H.subtypeL g)‖ * ‖H.subtypeL h‖ := by
            simpa using
              (norm_inner_le_norm (𝕜 := ℝ) (coeffMulLpL A (H.subtypeL g)) (H.subtypeL h))
    _ ≤ (A.Λ * ‖H.subtypeL g‖) * ‖H.subtypeL h‖ := by
          gcongr
          exact norm_coeffMulLpL_le A (H.subtypeL g)
    _ = A.Λ * ‖g‖ * ‖h‖ := by
          simp [mul_assoc]

theorem coeffBilinSubmodule_coercive
    {Ω : Set E} (A : EllipticCoeff d Ω)
    (H : Submodule ℝ (MeasureTheory.Lp E 2 (volume.restrict Ω))) :
    IsCoercive (coeffBilinSubmodule A H) := by
  refine ⟨A.lam, A.hlam, ?_⟩
  intro g
  let G : MeasureTheory.Lp E 2 (volume.restrict Ω) := H.subtypeL g
  let hAG_mem : MemLp (fun x => matMulE (A.a x) (G x)) 2 (volume.restrict Ω) :=
    coeffAction_memLp A (Lp.memLp G)
  have hcoeff_ae :
      coeffMulLpL A G =ᵐ[volume.restrict Ω] fun x => matMulE (A.a x) (G x) :=
    MemLp.coeFn_toLp hAG_mem
  have hright_int0 :
      Integrable (fun x => ⟪coeffMulLpL A G x, G x⟫_ℝ) (volume.restrict Ω) :=
    MeasureTheory.L2.integrable_inner (coeffMulLpL A G) G
  have hright_int :
      Integrable (fun x => ⟪matMulE (A.a x) (G x), G x⟫_ℝ) (volume.restrict Ω) := by
    refine hright_int0.congr ?_
    filter_upwards [hcoeff_ae] with x hx
    simp [hx]
  have hleft_int :
      Integrable (fun x => A.lam * ⟪G x, G x⟫_ℝ) (volume.restrict Ω) := by
    simpa using (MeasureTheory.L2.integrable_inner G G).const_mul A.lam
  have hcoer_ae :
      ∀ᵐ x ∂(volume.restrict Ω),
        A.lam * ⟪G x, G x⟫_ℝ ≤ ⟪matMulE (A.a x) (G x), G x⟫_ℝ := by
    filter_upwards [A.coercive] with x hx
    simpa [real_inner_comm, real_inner_self_eq_norm_sq] using hx (G x)
  have hmono :
      ∫ x, A.lam * ⟪G x, G x⟫_ℝ ∂(volume.restrict Ω) ≤
        ∫ x, ⟪matMulE (A.a x) (G x), G x⟫_ℝ ∂(volume.restrict Ω) :=
    integral_mono_ae hleft_int hright_int hcoer_ae
  have hright_eq :
      ∫ x, ⟪matMulE (A.a x) (G x), G x⟫_ℝ ∂(volume.restrict Ω) =
        coeffBilinSubmodule A H g g := by
    change ∫ x, ⟪matMulE (A.a x) (G x), G x⟫_ℝ ∂(volume.restrict Ω) =
      ⟪coeffMulLpL A G, G⟫_ℝ
    rw [MeasureTheory.L2.inner_def]
    apply integral_congr_ae
    filter_upwards [hcoeff_ae] with x hx
    simp [hx]
  calc
    A.lam * ‖g‖ * ‖g‖ = A.lam * ‖G‖ * ‖G‖ := by simp [G]
    _ = A.lam * ⟪G, G⟫_ℝ := by
          have hinner : ⟪G, G⟫_ℝ = ‖G‖ * ‖G‖ := by
            simp [pow_two]
          rw [hinner]
          ring
    _ = ∫ x, A.lam * ⟪G x, G x⟫_ℝ ∂(volume.restrict Ω) := by
          rw [MeasureTheory.L2.inner_def, integral_const_mul]
    _ ≤ ∫ x, ⟪matMulE (A.a x) (G x), G x⟫_ℝ ∂(volume.restrict Ω) := hmono
    _ = coeffBilinSubmodule A H g g := hright_eq

omit [NeZero d] in
private theorem eLpNorm_vector_le_sum_component_eLpNorm
    {Ω : Set E} {g : E → E}
    (hg : AEStronglyMeasurable g (volume.restrict Ω)) :
    eLpNorm g 2 (volume.restrict Ω) ≤
      ∑ i : Fin d, eLpNorm (fun x => g x i) 2 (volume.restrict Ω) := by
  let μ : Measure E := volume.restrict Ω
  let s : E → ℝ := ∑ i : Fin d, fun x => ‖g x i‖
  change eLpNorm g 2 μ ≤ ∑ i : Fin d, eLpNorm (fun x => g x i) 2 μ
  have hg_ofLp :
      AEStronglyMeasurable (fun x => (WithLp.ofLp (g x) : Fin d → ℝ)) μ := by
    have hcont : Continuous (fun y : E => (WithLp.ofLp y : Fin d → ℝ)) := by
      simpa using (PiLp.continuous_ofLp 2 (fun _ : Fin d => ℝ))
    exact hcont.comp_aestronglyMeasurable hg
  have hpoint :
      ∀ᵐ x ∂μ, ‖g x‖ ≤ s x := by
    filter_upwards with x
    have hsum_nonneg : 0 ≤ ∑ i : Fin d, ‖g x i‖ :=
      Finset.sum_nonneg fun i hi => norm_nonneg (g x i)
    have hsq :
        ‖g x‖ ^ 2 = ∑ i : Fin d, ‖g x i‖ ^ 2 := by
      simpa using (PiLp.norm_sq_eq_of_L2 (β := fun _ : Fin d => ℝ) (g x))
    have hsum_ge :
        ∀ i : Fin d, ‖g x i‖ ≤ ∑ j : Fin d, ‖g x j‖ := by
      intro i
      exact Finset.single_le_sum (fun j hj => norm_nonneg (g x j)) (by simp)
    have hsq_le :
        ∑ i : Fin d, ‖g x i‖ ^ 2 ≤ (∑ i : Fin d, ‖g x i‖) ^ 2 := by
      calc
        ∑ i : Fin d, ‖g x i‖ ^ 2 = ∑ i : Fin d, ‖g x i‖ * ‖g x i‖ := by
          simp [pow_two]
        _ ≤ ∑ i : Fin d, ‖g x i‖ * ∑ j : Fin d, ‖g x j‖ := by
              refine Finset.sum_le_sum ?_
              intro i hi
              gcongr
              exact hsum_ge i
        _ = (∑ i : Fin d, ‖g x i‖) * ∑ j : Fin d, ‖g x j‖ := by
              rw [← Finset.sum_mul]
        _ = (∑ i : Fin d, ‖g x i‖) ^ 2 := by
              ring
    have hnorm_le : ‖g x‖ ≤ ∑ i : Fin d, ‖g x i‖ := by
      nlinarith [hsq, hsq_le, norm_nonneg (g x), hsum_nonneg]
    calc
      ‖g x‖ ≤ ∑ i : Fin d, ‖g x i‖ := hnorm_le
      _ = s x := by simp [s]
  have hs_meas :
      AEStronglyMeasurable s μ := by
    refine Finset.aestronglyMeasurable_sum (s := (Finset.univ : Finset (Fin d)))
      (f := fun i x => ‖g x i‖) ?_
    intro i hi
    exact ((continuous_apply i).comp_aestronglyMeasurable hg_ofLp).norm
  have hmono :
      eLpNorm g 2 μ ≤ eLpNorm s 2 μ := by
    exact eLpNorm_mono_ae_real hpoint
  have hsum :
      eLpNorm s 2 μ ≤ ∑ i : Fin d, eLpNorm (fun x => ‖g x i‖) 2 μ := by
    let p : ENNReal := 2
    have hfs :
        ∀ i : Fin d, i ∈ (Finset.univ : Finset (Fin d)) →
          AEStronglyMeasurable (fun x => ‖g x i‖) μ := by
      intro i hi
      exact ((continuous_apply i).comp_aestronglyMeasurable hg_ofLp).norm
    have hp1 : (1 : ENNReal) ≤ p := by simp [p]
    have hsum' :
        eLpNorm (Finset.sum (Finset.univ : Finset (Fin d)) fun i => fun x => ‖g x i‖) p μ ≤
          Finset.sum (Finset.univ : Finset (Fin d)) fun i => eLpNorm (fun x => ‖g x i‖) p μ := by
      exact eLpNorm_sum_le (μ := μ) hfs hp1
    simpa [s, p] using hsum'
  calc
    eLpNorm g 2 μ ≤ eLpNorm s 2 μ := hmono
    _ ≤ ∑ i : Fin d, eLpNorm (fun x => ‖g x i‖) 2 μ := hsum
    _ = ∑ i : Fin d, eLpNorm (fun x => g x i) 2 μ := by
          refine Finset.sum_congr rfl ?_
          intro i hi
          simpa using (eLpNorm_norm (μ := μ) (p := (2 : ENNReal)) (fun x => g x i))

omit [NeZero d] in
theorem tendsto_eLpNorm_vector_of_componentwise
    {Ω : Set E} {g : E → E} {gseq : ℕ → E → E}
    (hcomp_mem : ∀ n : ℕ, ∀ i : Fin d,
      MemLp (fun x => gseq n x i - g x i) 2 (volume.restrict Ω))
    (hcomp : ∀ i : Fin d,
      Tendsto (fun n => eLpNorm (fun x => gseq n x i - g x i) 2 (volume.restrict Ω))
        atTop (nhds 0)) :
    Tendsto (fun n => eLpNorm (fun x => gseq n x - g x) 2 (volume.restrict Ω))
      atTop (nhds 0) := by
  have hupper :
      ∀ n,
        eLpNorm (fun x => gseq n x - g x) 2 (volume.restrict Ω) ≤
          ∑ i : Fin d,
            eLpNorm (fun x => gseq n x i - g x i) 2 (volume.restrict Ω) := by
    intro n
    exact eLpNorm_vector_le_sum_component_eLpNorm
      ((MeasureTheory.MemLp.of_eval_piLp (fun i => hcomp_mem n i)).aestronglyMeasurable)
  have hsum :
      Tendsto
        (fun n => ∑ i : Fin d,
          eLpNorm (fun x => gseq n x i - g x i) 2 (volume.restrict Ω))
        atTop (nhds 0) := by
    simpa using tendsto_finset_sum (Finset.univ : Finset (Fin d)) (fun i _ => hcomp i)
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le tendsto_const_nhds hsum (fun n => zero_le) hupper

theorem coeffMulLpL_inner_gradLpOfWitness_eq_bilinFormOfCoeff
    {Ω : Set E} (A : EllipticCoeff d Ω)
    {u v : E → ℝ}
    (hu : MemW1pWitness 2 u Ω)
    (hv : MemW1pWitness 2 v Ω) :
    ⟪coeffMulLpL A (gradLpOfWitness hu), gradLpOfWitness hv⟫_ℝ =
      bilinFormOfCoeff A hu hv := by
  rw [MeasureTheory.L2.inner_def, bilinFormOfCoeff]
  apply integral_congr_ae
  filter_upwards
    [coeffApplyLp_ae_eq A (gradLpOfWitness hu),
      MemLp.coeFn_toLp hu.weakGrad_memLp,
      MemLp.coeFn_toLp hv.weakGrad_memLp] with x hxA hxu hxv
  have hxcoeff :
      ((coeffMulLpL A) (gradLpOfWitness hu)) x = matMulE (A.a x) (hu.weakGrad x) := by
    simpa [coeffMulLpL, gradLpOfWitness, hxu] using hxA
  have hxgrad :
      (gradLpOfWitness hv) x = hv.weakGrad x := by
    simpa [gradLpOfWitness] using hxv
  simp [bilinFormIntegrandOfCoeff, hxcoeff, hxgrad]

end DeGiorgi
